# Generated by Django 5.0.6 on 2024-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driverName',
            field=models.CharField(max_length=255),
        ),
    ]
