# Generated by Django 5.0.6 on 2024-05-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_user_drivername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Whitelist',
        ),
    ]
