# Generated by Django 5.0.6 on 2024-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_searchlog_delete_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'whitelist',
                'managed': False,
            },
        ),
    ]
